services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./turbo.json:/app/turbo.json
    environment:
      - NODE_ENV=production
    command: pnpm turbo run start:backend

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '8501:8501'
    volumes:
      - ./apps/web:/app/apps/web
      - ./turbo.json:/app/turbo.json
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - backend
      - ai

  ai:
    build:
      context: .
      dockerfile: services/ai/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./services/ai:/app/services/ai
      - ./turbo.json:/app/turbo.json
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000
