analyze_search_results:
  description: >
    Analyze the provided search results to identify which information is relevant to the user query: "{user_query}"
    
    Search Results:
    {search_results}
    
    Your task:
    1. Identify which results are relevant to the user query "{user_query}"
    2. Ignore any results that are not related to the query
    3. Extract key information from the relevant results
    4. Note any patterns or insights from the relevant information
  expected_output: >
    A structured analysis that includes:
    - List of relevant results with brief explanations
    - Key information extracted from relevant results
    - Any patterns or insights identified
    - Assessment of information quality and completeness
  agent: rag_analyzer

generate_chat_response:
  description: >
    Based on the search results, generate a natural and helpful response to the user query: "{user_query}"
    
    Search Results:
    {search_results}
    
    Your task:
    1. Create a natural, conversational response that directly answers the user's question
    2. Use the relevant information from the search results
    3. If no relevant information was found, politely explain this to the user
    4. Maintain a helpful and professional tone
    5. Respond in Thai language
  expected_output: >
    A natural, helpful response in Thai language that:
    - Directly addresses the user's query
    - Uses relevant information from the search results
    - Is conversational and easy to understand
    - Maintains a professional and helpful tone
  agent: chat_responder
